### ISSUE TITLE
How to build for Android?

### ISSUE THREAD

**Issue by Ishu07** [aws-samples/amazon-polly-metahumans#17]
How do I build the aws-cpp modules for android?

**Comment by cwalkere** [comment]
We didn't test with android, you're free to explore to try to get it to work on android. I'd recommend going to the aws cli github package for help.

**Comment by Ishu07** [comment]
I've tried building aws-cpp Android. Now the question:
Would it require code level changes, or just add the build files and modify the build.bat file?

**Comment by Ishu07** [comment]
Closed by mistake

**Comment by Ishu07** [comment]
Closed by mistake

**Comment by Ishu07** [comment]
@Krxtopher Please a little help :D

**Comment by Krxtopher** [comment]
Hey, Ishu07. As cwalkere mentioned above, we did not target Android when designing this sample project. So I'm afraid I don't have any insights to help you get it working on that platform.

If you'd like to see us update the project in the future to support Android, I recommend creating a new issue requesting Android support and mark it with the "enhancement" tag. That will help us track the request and gauge community interest in such a feature, informing our future roadmap planning.

**Comment by Ishu07** [comment]
Okay, i have managed to build for Android. Just one step I'm not able to figure out.

Authentication: current implementation requires ~/.aws/config and the other file 
For Android, it's kinda not possible, so I'm trying out a way to hardcode it inside the header or a BO module for it to take my aws secret and access key.

A little push in the right direction might help

Thanks

**Comment by kishorkuttan** [comment]
> 

Can you share how you pack this on android.?
