### ISSUE TITLE
The polly sdk not working correctly with some unicode  language ? 

### ISSUE THREAD

**Issue by eggcaker** [aws-samples/amazon-polly-metahumans#20]
I download the repo and built all SDKs. then add more voiceIds (like Zhiyu for chinse),   after the pixel streaming started, when enter some Chinese text in the text box, the polly can only speak few characters. Same for Japanese's voice id. But for English works. Did I missing some configurations ?

**Comment by CasonTsai** [comment]
i meet the same  issue,do you finished it?
